---
- name: Update and restart Docker Compose stack(s)
  hosts: all
  become: yes
  collections:
    - community.docker
  tasks:
    - name: Ensure pip is installed
      package:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: /usr/bin/pip3
        state: present

    # - name: Verify Docker SDK installation
    #   command: /usr/bin/python3 -c "import docker; print(docker.__version__)"
    #   register: docker_version
    #   changed_when: false

    # - name: Show Docker SDK version
    #   debug:
    #     msg: "Docker SDK version: {{ docker_version.stdout }}"

    - name: Update and restart Docker Compose stack(s)
      community.docker.docker_compose:
        project_src: "{{ item }}"
        pull: yes
        state: present
      loop: "{{ compose_dirs }}"
