---
- name: Pull and restart Docker Compose stacks
  hosts: all
  become: yes
  collection:
    - community.docker
  tasks:
    - name: Update and restart Docker Compose stacks
      community.docker.docker_compose:
        project_src: "{{ item }}"
        pull: yes
        state: present
#      loop: "{{ compose_dirs }}"
