---
- name: Run Docker Compose Pull and Up for Multiple Directories
  hosts: "{{ target_hosts }}"  # Dynamically populated by Semaphore UI
  become: true

  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker
        state: present
      ignore_errors: yes

    - name: Alternaitve Check if Docker is installed
      ansible.builtin.command:
        cmd: docker --version
      register: docker_version
      ignore_errors: yes

    - name: Show Docker version
      debug:
        var: docker_version.stdout
      ignore_errors: yes

    - name: Ensure Docker Compose is installed
      ansible.builtin.package:
        name: docker-compose
        state: present
      ignore_errors: yes

    - name: Pull latest images for each compose directory
      ansible.builtin.command:
        cmd: docker compose pull
        chdir: "{{ item }}"
      loop: "{{ compose_dirs }}"

    - name: Start containers for each compose directory
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: "{{ item }}"
      loop: "{{ compose_dirs }}"
