---
- name: Install Docker and Docker Compose
  hosts: "{{ target_hosts }}"  # Dynamically populated by Semaphore UI
  become: true

  tasks:
    - name: Gather OS distribution facts
      ansible.builtin.setup:
        gather_subset:
          - "min"

    - name: Debug distribution information
      debug:
        msg:
          - "Distribution: {{ ansible_distribution }}"
          - "Release: {{ ansible_distribution_release }}"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      ansible.builtin.command:
        cmd: curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg
      register: add_gpg_result
      failed_when: add_gpg_result.rc != 0
      ignore_errors: yes

    - name: Fail if GPG key could not be added
      ansible.builtin.fail:
        msg: "Failed to add Docker GPG key"
      when: add_gpg_result is failed

    - name: Add Docker repository for Debian 12
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bookworm stable"
        state: present
        filename: docker
      when: ansible_distribution == "Debian" and ansible_distribution_release == "bookworm"
      register: add_repo_result_debian

    - name: Add Docker repository for Ubuntu
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
      when: ansible_distribution == "Ubuntu"
      register: add_repo_result_ubuntu

    - name: Debug repository addition results
      debug:
        msg:
          - "Debian repository result: {{ add_repo_result_debian }}"
          - "Ubuntu repository result: {{ add_repo_result_ubuntu }}"

    - name: Fail if repository could not be added
      ansible.builtin.fail:
        msg: "Failed to add Docker repository"
      when: 
        - ansible_distribution == "Debian" and add_repo_result_debian is failed
        - ansible_distribution == "Ubuntu" and add_repo_result_ubuntu is failed

    - name: Update apt cache after adding Docker repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
      register: docker_install_result
      failed_when: docker_install_result.rc != 0
      ignore_errors: yes

    - name: Fail if Docker installation fails
      ansible.builtin.fail:
        msg: "Docker installation failed"
      when: docker_install_result is failed

    - name: Ensure Docker service is started and enabled
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install Docker Compose plugin
      ansible.builtin.apt:
        name: docker-compose-plugin
        state: present

    - name: Add current user to the Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
        state: present
      become: yes
