---
- name: Pull and restart Docker Compose stacks
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  collections:
    - community.docker
  tasks:
    - name: Ensure pip is installed
      apt:
        name: python3-pip
        state: present
      when: ansible_facts['pkg_mgr'] == 'apt'

    - name: Ensure pip is installed
      yum:
        name: python3-pip
        state: present
      when: ansible_facts['pkg_mgr'] == 'yum'

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: /usr/bin/pip3
        state: present

    - name: Update and restart Docker Compose stacks
      community.docker.docker_compose:
        project_src: "{{ item }}"
        pull: yes
        state: present
      loop: "{{ compose_dirs }}"
