---
- name: Install Docker and Docker Compose using official Docker script
  hosts: "{{ target_hosts }}"  # Dynamically populated by Semaphore UI
  become: true

  tasks:
    - name: Install required packages for HTTPS
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
        state: present

    - name: Download Docker's official install script
      ansible.builtin.get_url:
        url: https://get.docker.com/
        dest: /tmp/get-docker.sh
        mode: '0755'

    - name: Run Docker's official install script
      ansible.builtin.command: /tmp/get-docker.sh
      register: install_docker_script
      ignore_errors: yes

    - name: Show script install output
      debug:
        var: install_docker_script

    - name: Ensure Docker service is started and enabled
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install Docker Compose plugin
      ansible.builtin.apt:
        name: docker-compose-plugin
        state: present

    - name: Add current user to the Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      become: yes
