---
- name: Pull and restart Docker Compose stacks
  hosts: all  # Replace 'all' with your specific host group if needed
  become: yes
  collections:
    - community.docker
  tasks:
    - name: Update and restart Docker Compose stacks
      community.docker.docker_compose:
        project_src: "{{ item }}"
        pull: yes
        state: present
      loop: "{{ compose_dirs }}"
