---
- name: Install Docker and Docker Compose
  hosts: "{{ target_hosts }}"
  become: true

  tasks:
    - name: Check if Docker is already installed
      command: which docker
      register: docker_check
      changed_when: false
      failed_when: false

    - name: Install required system packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - python3-docker  # Required for Ansible Docker modules
        state: present
        update_cache: yes

    - name: Download Docker install script
      ansible.builtin.get_url:
        url: https://get.docker.com/
        dest: /tmp/get-docker.sh
        mode: '0755'
      when: docker_check.rc != 0

    - name: Run Docker install script
      ansible.builtin.command: /tmp/get-docker.sh
      when: docker_check.rc != 0

    - name: Ensure Docker service is started and enabled
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add current user to the Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes