---
- name: Run Docker Compose Pull and Up for Multiple Directories
  hosts: "{{ target_hosts }}"  # Dynamically populated by Semaphore UI
  become: true

  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker
        state: present

    - name: Ensure Docker Compose is installed
      ansible.builtin.package:
        name: docker-compose
        state: present

    - name: Pull latest images for each compose directory
      ansible.builtin.command:
        cmd: docker compose pull
        args:
          chdir: "{{ item }}"
      loop: "{{ compose_dirs }}"

    - name: Start containers for each compose directory
      ansible.builtin.command:
        cmd: docker compose up -d
        args:
          chdir: "{{ item }}"
      loop: "{{ compose_dirs }}"
