---
- name: Run Docker Compose Pull and Up
  hosts: {{ target_hosts }}  # Specify your inventory group or host here
  become: true

  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker
        state: present

    - name: Ensure Docker Compose is installed
      ansible.builtin.package:
        name: docker-compose
        state: present

    - name: Pull latest images with Docker Compose
      ansible.builtin.command:
        cmd: docker compose pull
        chdir: /path/to/your/docker-compose-directory  # Change to your compose directory

    - name: Start containers with Docker Compose
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: /home/michael/docker/traefik2  # Change to your compose directory
