---
- hosts: "{{ target_hosts }}"
    become: true
    tasks:
    - name: Ensure .ssh directory exists
        file:
        path: "{{ ansible_user_dir }}/.ssh"
        state: directory
        mode: '0700'

    - name: Add public key to authorized_keys
        authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ ssh_key }}"
