---
- name: System Maintenance (APT Update & Upgrade)
  hosts: "{{ target_hosts }}"
  become: true

  tasks:
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes
        autoremove: yes
        autoclean: yes
        cache_valid_time: 3600

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Notify if reboot is required
      ansible.builtin.debug:
        msg: "NOTE: A reboot is required to complete updates on {{ inventory_hostname }}"
      when: reboot_required_file.stat.exists