---
- name: System Maintenance (APT Update & Upgrade)
  hosts: "{{ target_hosts }}"
  become: true

  tasks:
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes
        autoremove: yes
        autoclean: yes
        cache_valid_time: 3600

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible after package updates"
        test_command: uptime
      when: reboot_required_file.stat.exists
