---
- hosts: "{{ target_hosts }}"
  become: true
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Upgrade all APT packages (dist-upgrade)
      apt:
        upgrade: dist

    - name: Clean up unnecessary packages
      apt:
        autoremove: yes
        autoclean: yes
