---
# Update all hosts except brainiac-local
- name: Update all hosts
  hosts: "{{ target_hosts }}"
  become: true
  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Upgrade all apt packages
      apt:
        upgrade: dist
        force_apt_get: yes
      register: apt_upgrade_result
      failed_when: 
        - apt_upgrade_result is failed
        - inventory_hostname != 'brainiac-local'
      
    - name: Check if reboot required
      register: reboot_required_file
      stat: path=/var/run/reboot-required
      failed_when: false

    - name: Reboot
      reboot:
      when: reboot_required_file.stat.exists