---
- name: Technitium DNS Maintenance
  hosts: "{{ target_hosts | default('dns_servers') }}"
  become: true
  serial: 1  # Updates one host at a time
  vars:
    install_dir: "/opt/technitium/dns"
    version_file: "/root/.technitium"
    download_url: "https://download.technitium.com/dns/DnsServerPortable.tar.gz"
    service_name: "technitium"

  tasks:
    - name: Get latest Technitium version
      ansible.builtin.shell: "curl -fsSL https://technitium.com/dns/ | grep -oP 'Version \\K[\\d.]+'"
      register: latest_version_check
      changed_when: false
      run_once: true
      delegate_to: localhost

    - name: Get installed Technitium version
      ansible.builtin.command: "cat {{ version_file }}"
      register: installed_version_check
      failed_when: false
      changed_when: false

    - name: Display versions
      ansible.builtin.debug:
        msg: "Host: {{ inventory_hostname }} | Installed: {{ installed_version_check.stdout | default('None') }} | Latest: {{ latest_version_check.stdout }}"

    - name: Update Technitium DNS
      block:
        - name: Stop Technitium DNS service
          ansible.builtin.systemd:
            name: "{{ service_name }}"
            state: stopped

        - name: Download and extract new version
          ansible.builtin.unarchive:
            src: "{{ download_url }}"
            dest: "{{ install_dir }}"
            remote_src: yes
            owner: root
            group: root

        - name: Update version file
          ansible.builtin.copy:
            content: "{{ latest_version_check.stdout }}"
            dest: "{{ version_file }}"
            mode: '0644'

        - name: Start Technitium DNS service
          ansible.builtin.systemd:
            name: "{{ service_name }}"
            state: started
            daemon_reload: yes

        - name: Wait for DNS service to be ready (Port 53)
          ansible.builtin.wait_for:
            port: 53
            delay: 5
            timeout: 60
            host: "127.0.0.1"
          register: dns_check

        - name: Verify Web UI is reachable (Health Check)
          ansible.builtin.uri:
            url: "http://127.0.0.1:5380"
            status_code: 200
            timeout: 5
          register: health_check
          retries: 3
          delay: 5
          until: health_check.status == 200

      when: installed_version_check.stdout != latest_version_check.stdout

  # If any task in the block fails, Ansible stops processing for that host.
  # Since serial: 1 is set, if the first host fails verification, 
  # the playbook stops and the second host is never touched.
